# Generated by Django 5.1.6 on 2025-03-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierprofile',
            name='partner_company',
            field=models.CharField(choices=[('HOEKSTRA', 'Hoekstra'), ('VINTAGE_EXPRESS', 'Vintage Express'), ('MAGIC_MOVERS', 'Magic Movers'), ('SW_DE_VRIES_LOGISTICS', 'SW de Vries Logistics'), ('LIBERO_LOGISTICS', 'Libero Logistics'), ('TRANSPOKSI', 'Transpoksi'), ('TRUSK', 'Trusk'), ('COCOLIS', 'Cocolis'), ('MH_TRANSPORT', 'MH Transport')], max_length=50, null=True, verbose_name='Partner Company'),
        ),
    ]
